USE [master]
GO

/****** Object:  Database [Lista]    Script Date: 09/08/2021 20:26:30 ******/
CREATE DATABASE [Lista] ON  PRIMARY 
( NAME = N'Lista', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Lista.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Lista_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Lista_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lista].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lista] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lista] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lista] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lista] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lista] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lista] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Lista] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lista] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lista] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lista] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lista] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lista] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lista] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lista] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lista] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Lista] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lista] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lista] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lista] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lista] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lista] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lista] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lista] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Lista] SET  MULTI_USER 
GO

ALTER DATABASE [Lista] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lista] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Lista] SET  READ_WRITE 
GO


